FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# The default command when deployed to Hugging Face
CMD ["python", "inference.py"]